server:
  port: 8066
  tomcat:
    uri-encoding: utf-8
    max-threads: 200
    max-connections: 500

spring:
  application:
    name: Spider
  main:
    allow-bean-definition-overriding: true
  datasource:
    druid:
      url: jdbc:mysql://192.168.12.156:32707/spider?useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: KqXLQCdlOdfjkvrg
      max-active: 200
      max-wait: 2000
      initial-size: 30
      min-idle: 15
      connection-properties: config.decrypt=false
      filter:
        config:
          enabled: true
  redis:
    port: 6379
    host: 192.168.12.156:32708

#logging:
#  config: classpath:config/logback-spring.xml
#  citybrain:
#    level: INFO
#    path: ./logs


# 通用 Mapper 配置
mapper:
  mappers: spider.base.MyMapper
  not-empty: true
# mybatis 配置
mybatis:
  type-aliases-package: spider.pojo
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
